name: Deploy to Server

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch, change this to the branch you use for deployment.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up SSH
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # SSH into the server and run deployment commands
      - name: Deploy to server
        run: |
          echo "SERVER_USER: ${{ secrets.SERVER_USER }}"
          echo "SERVER_DOMAIN: ${{ secrets.SERVER_DOMAIN }}"
          echo "Checking for /root/CWebServer directory:"

          ssh -o StrictHostKeyChecking=no -i ~/.ssh/github_actions root@${{ secrets.SERVER_IP }} << 'EOF'
            # Kill existing tmux session (if any)
            tmux kill-session -t myserver || true
            # Create a new tmux session with the latest code
            tmux new-session -d -s myserver 'cd /root/CWebServer && git pull && make rebuild && ./server ${{ secrets.SERVER_IP }} ${{ secrets.SERVER_PORT }}'
            tmux attach-session -t myserver
          EOF
